
insert into estado(id,nome,sigla,codigo_ibge) values (11, 'Rondônia', 'RO', 11);
insert into estado(id,nome,sigla,codigo_ibge) values (12, 'Acre', 'AC', 12);
insert into estado(id,nome,sigla,codigo_ibge) values (13, 'Amazonas', 'AM', 13);
insert into estado(id,nome,sigla,codigo_ibge) values (14, 'Roraima', 'RR', 14);
insert into estado(id,nome,sigla,codigo_ibge) values (15, 'Pará', 'PA', 15);
insert into estado(id,nome,sigla,codigo_ibge) values (16, 'Amapá', 'AP', 16);
insert into estado(id,nome,sigla,codigo_ibge) values (17, 'Tocantins', 'TP', 17);
insert into estado(id,nome,sigla,codigo_ibge) values (21, 'Maranhão', 'MA', 21);
insert into estado(id,nome,sigla,codigo_ibge) values (22, 'Piauí', 'PI', 22);
insert into estado(id,nome,sigla,codigo_ibge) values (23, 'Ceará', 'CE', 23);
insert into estado(id,nome,sigla,codigo_ibge) values (24, 'Rio Grande do Norte', 'RN', 24);
insert into estado(id,nome,sigla,codigo_ibge) values (25, 'Paraíba', 'PB', 25);
insert into estado(id,nome,sigla,codigo_ibge) values (26, 'Pernambuco', 'PE', 26);
insert into estado(id,nome,sigla,codigo_ibge) values (27, 'Alagoas', 'AL', 27);
insert into estado(id,nome,sigla,codigo_ibge) values (28, 'Sergipe', 'SE', 28);
insert into estado(id,nome,sigla,codigo_ibge) values (29, 'Bahia', 'BA', 29);
insert into estado(id,nome,sigla,codigo_ibge) values (31, 'Minas Gerais', 'MG', 31);
insert into estado(id,nome,sigla,codigo_ibge) values (32, 'Espírito Santo', 'ES', 32);
insert into estado(id,nome,sigla,codigo_ibge) values (33, 'Rio de Janeiro', 'RJ', 33);
insert into estado(id,nome,sigla,codigo_ibge) values (35, 'São Paulo', 'SP', 35);
insert into estado(id,nome,sigla,codigo_ibge) values (41, 'Paraná', 'PR', 41);
insert into estado(id,nome,sigla,codigo_ibge) values (42, 'Santa Catarina', 'SC', 42);
insert into estado(id,nome,sigla,codigo_ibge) values (43, 'Rio Grande do Sul', 'RS', 43);
insert into estado(id,nome,sigla,codigo_ibge) values (50, 'Mato Grosso do Sul', 'MS', 50);
insert into estado(id,nome,sigla,codigo_ibge) values (51, 'Mato Grosso', 'MT', 51);
insert into estado(id,nome,sigla,codigo_ibge) values (52, 'Goiás', 'GO', 52);
insert into estado(id,nome,sigla,codigo_ibge) values (53, 'Distrito Federal', 'DF', 53);
COMMIT;
